trigger:
  tags:
    include:
      - v*

pool:
  vmImage: "windows-2019"

stages:
  - stage: STAGE_NAME
    displayName: PRETTY_STAGE_NAME
    jobs:
      - job: CI
        steps:
          - task: Npm@1
            # TODO
          - task: Npm@1
            # TODO
          - task: ArchiveFiles@2
            # TODO
          - task: AzureWebApp@1
            # TODO
