trigger:
  tags:
    include:
      - v*

pool:
  vmImage: "windows-2019"

stages:
  - stage: STAGE_NAME
    displayName: PRETTY_STAGE_NAME
    jobs:
      - job: CI
        # This job installs all dependencies as a clean slate, runs tests and finally builds the app. If all steps are successful than the job is successful.
        steps:
          - task: Npm@1
            inputs:
              command: "custom"
              workingDir: "spa-client"
              customCommand: "run cit"
          - task: Npm@1
            inputs:
              command: "custom"
              workingDir: "spa-client"
              customCommand: "run build"
          - task: Npm@1
            inputs:
              command: "custom"
              workingDir: "spa-client"
              customCommand: "run export"
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: "spa-client/out"
              includeRootFolder: false
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)/app.zip"
          - task: AzureWebApp@1
            inputs:
              appType: "webApp"
              appName: APP_NAME
              package: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId)/app.zip"
              deploymentMethod: "auto"
